import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Anakotmai from "next/font/local"

const anakotmai = Anakotmai({
  src: [{
    path: "../../public/font/Anakotmai.ttf",
    weight: "400",
  }],
  variable: "--font-anakotmai"
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "พรรคจักรวาลคือความสุข | Jakkrawan Party",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={anakotmai.className}>{children}</body>
    </html>
  );
}
